
LKRun/Name                    run  # name of the run
LKRun/RunID                   0  # run number
LKRun/Tag                     tag  # tag
LKRun/OutputPath              /Users/jungwoo/Research/lilak/data  # path to the output. Default path {lilak_data} is lilak/data/
#LKRun/InputPath               /path/to/in/  # LKRun will search files from input paths when LKRun/SearchRun
LKRun/SearchRun               mfm  # search input files with LKRun/RunID. opt=mfm: search mfm files, opt=[tag]: search run_runNo.*.[tag].root
LKRun/AutoTerminate           true  # automatically terminate root after end of run
#LKRun/Division                0  # division within the run [optional]
LKRun/InputFile               to/input/file  # input file. Cannot be used with LKRun/SearchRun
#LKRun/FriendFile              to/friend/file  # input friend file
#LKRun/RunIDList               1, 2, 3, 4  # list of run numbers separated by ,
#LKRun/RunIDRange              1, 10  # list of run numbers ranged by ,
#LKRun/EntriesLimit            100000  # limit number of run entries
LKRun/EventCountForMessage    20000
#LKRun/UpdateOutputFile        0  # update root file with option update
#LKRun/FileName                  # file name will be fixed to this name if it is not null string

LKGETConversionTask/InputFileName       

lilak/add LKGETConversionTask
lilak/run 0

persistency/FrameHeader       true
persistency/RawData           true
