// This macro was generated by:
//   lilak read /Users/jungwoo/data/stark/reco/stark_board_test_0054.reco.root
//
// Purpose:
//   Open a LILAK output ROOT file, connect the event tree branches,
//   read ParameterContainer and RunHeader, and provide an editable event-loop skeleton.
//
// Use dump > 0 to loop over only dump entries and call Print() for every branch element.
// Use dump = 0 for normal looping without automatic element Print().
// Getter examples come from meta/lilak_read_getters.conf.
// Draw examples come from meta/lilak_read_members.conf.
//
// XXX USER EDIT AREA INDEX:
//   XXX-1: Global run controls. Change fInputFileName, fMaxEvents, fDump, fPrintAfter, fRunLoop, fDrawBranch.
//   XXX-2: Draw commands. Add fReadTree->Draw("...") examples in draw_branch().
//   XXX-3: Branch loop for FrameHeader (LKEventHeader).
//   XXX-4: Branch loop for RawData (GETChannel).
//   XXX-5: Branch loop for SiChannel (LKSiChannel).
//   XXX-6: Branch loop for SiHit (SKSiHit).


//===============================================================================
// XXX-1 USER EDIT AREA BEGIN: global input file and loop controls.
//===============================================================================
TString fInputFileName = "/Users/jungwoo/data/stark/reco/stark_board_test_0054.reco.root";
Long64_t fMaxEvents = -1;
int fDump = 0;
Long64_t fPrintAfter = 2000;
bool fRunLoop = false;
bool fDrawBranch = true;
bool fActiveFrameHeader = true;
bool fActiveRawData = true;
bool fActiveSiChannel = true;
bool fActiveSiHit = true;

//===============================================================================
// XXX-1 USER EDIT AREA END
//===============================================================================

TFile* fReadFile = nullptr;
TObject* fReadPar = nullptr;
TObject* fReadRunHeader = nullptr;
TTree* fReadTree = nullptr;

TClonesArray* fFrameHeaderArray = nullptr;
TClonesArray* fRawDataArray = nullptr;
TClonesArray* fSiChannelArray = nullptr;
TClonesArray* fSiHitArray = nullptr;

void open_file_and_set_branch(TString fileName);
void read_header_and_parameters(bool print = false);
void read_data(Long64_t maxEvents = -1, int dump = 0, Long64_t printAfter = 2000);
void draw_branch();

void read_stark_board_test_0054_reco()
{
    open_file_and_set_branch(fInputFileName);
    read_header_and_parameters();
    if (fRunLoop)
        read_data(fMaxEvents, fDump, fPrintAfter);
    if (fDrawBranch)
        draw_branch();
}

void open_file_and_set_branch(TString fileName)
{
    fReadFile = TFile::Open(fileName, "read");
    if (fReadFile == nullptr || fReadFile->IsZombie()) {
        std::cout << "Cannot open " << fileName << std::endl;
        fReadFile = nullptr;
        return;
    }

    fReadTree = dynamic_cast<TTree*>(fReadFile->Get("event"));
    if (fReadTree == nullptr) {
        TIter nextKey(fReadFile->GetListOfKeys());
        TKey* key = nullptr;
        while ((key = dynamic_cast<TKey*>(nextKey())) != nullptr) {
            auto object = key->ReadObj();
            fReadTree = dynamic_cast<TTree*>(object);
            if (fReadTree != nullptr)
                break;
        }
    }
    if (fReadTree == nullptr) {
        std::cout << "No TTree found in " << fileName << std::endl;
        return;
    }

    fReadTree->SetBranchAddress("FrameHeader", &fFrameHeaderArray);
    fReadTree->SetBranchAddress("RawData", &fRawDataArray);
    fReadTree->SetBranchAddress("SiChannel", &fSiChannelArray);
    fReadTree->SetBranchAddress("SiHit", &fSiHitArray);

}

void read_header_and_parameters(bool print)
{
    if (fReadFile == nullptr) {
        std::cout << "No file is open." << std::endl;
        return;
    }

    fReadPar = fReadFile->Get("ParameterContainer");
    fReadRunHeader = fReadFile->Get("RunHeader");

    std::cout << "# LILAK output file" << std::endl;
    std::cout << "File: " << fReadFile->GetName() << std::endl;
    std::cout << "ParameterContainer: " << (fReadPar != nullptr ? "loaded" : "missing") << std::endl;
    std::cout << "RunHeader: " << (fReadRunHeader != nullptr ? "loaded" : "missing") << std::endl;
    std::cout << "Event tree: " << (fReadTree != nullptr ? fReadTree->GetName() : "missing") << std::endl;
    std::cout << "# Branches" << std::endl;
    std::cout << "  FrameHeader : TClonesArray<LKEventHeader>" << std::endl;
    std::cout << "  RawData : TClonesArray<GETChannel>" << std::endl;
    std::cout << "  SiChannel : TClonesArray<LKSiChannel>" << std::endl;
    std::cout << "  SiHit : TClonesArray<SKSiHit>" << std::endl;

    if (!print)
        return;

    if (fReadPar != nullptr) {
        std::cout << std::endl << "# ParameterContainer" << std::endl;
        fReadPar->Print();
    }
    if (fReadRunHeader != nullptr) {
        std::cout << std::endl << "# RunHeader" << std::endl;
        fReadRunHeader->Print();
    }
}

void draw_branch()
{
    if (fReadTree == nullptr) {
        std::cout << "No event tree is loaded." << std::endl;
        return;
    }
    auto painter = LKPainter::GetPainter();

    //===============================================================================
    // XXX-2 USER EDIT AREA BEGIN: add branch drawing commands here.
    //===============================================================================
    // Examples:
    //   fReadTree->Draw("RawData.fChannel");
    //   fReadTree->Draw("SiHit.fEnergy");
    //   fReadTree->Draw("SiHit.fEnergy:SiHit.fX");
    //
    // Edit or comment out generated examples below for this file.
    if (fActiveFrameHeader) {
        // FrameHeader : LKEventHeader
        // reference: https://lilak-project.github.io/lilak_doxygen/classLKEventHeader.html
        std::vector<TString> drawMembers_FrameHeader = {"FrameHeader.fEventNumber" ,"FrameHeader.fBufferSize" ,"FrameHeader.fMTETimeStamp"};
        int nx, ny, n_draw_FrameHeader = drawMembers_FrameHeader.size();
        if (n_draw_FrameHeader>0) {
            painter -> PreDividePad(n_draw_FrameHeader, nx, ny);
            auto i_draw_FrameHeader = 1;
            auto cvs_FrameHeader = painter->CanvasResize("cvs_FrameHeader", 500*nx, 380*ny, 1.0);
            painter -> DividePad(cvs_FrameHeader, n_draw_FrameHeader);
            for (auto member : drawMembers_FrameHeader)
            {
                std::cout << "Draw: " << member << std::endl;
                cvs_FrameHeader->cd(i_draw_FrameHeader++);
                if (member.Contains(":"))
                    fReadTree->Draw(member, "", "colz");
                else
                    fReadTree->Draw(member);
            }
            cvs_FrameHeader->Modified();
            cvs_FrameHeader->Update();
        }
    }

    if (fActiveRawData) {
        // RawData : GETChannel
        // reference: https://lilak-project.github.io/lilak_doxygen/classGETChannel.html
        std::vector<TString> drawMembers_RawData = {"RawData.fCobo" ,"RawData.fAsad" ,"RawData.fAget" ,"RawData.fChan"};
        int nx, ny, n_draw_RawData = drawMembers_RawData.size();
        if (n_draw_RawData>0) {
            painter -> PreDividePad(n_draw_RawData, nx, ny);
            auto i_draw_RawData = 1;
            auto cvs_RawData = painter->CanvasResize("cvs_RawData", 500*nx, 380*ny, 1.0);
            painter -> DividePad(cvs_RawData, n_draw_RawData);
            for (auto member : drawMembers_RawData)
            {
                std::cout << "Draw: " << member << std::endl;
                cvs_RawData->cd(i_draw_RawData++);
                if (member.Contains(":"))
                    fReadTree->Draw(member, "", "colz");
                else
                    fReadTree->Draw(member);
            }
            cvs_RawData->Modified();
            cvs_RawData->Update();
        }
    }

    if (fActiveSiChannel) {
        // SiChannel : LKSiChannel
        // reference: https://lilak-project.github.io/lilak_doxygen/classLKSiChannel.html
        std::vector<TString> drawMembers_SiChannel = {"SiChannel.fLocalID" ,"SiChannel.fSide" ,"SiChannel.fStrip" ,"SiChannel.fDirection" ,"SiChannel.fInverted" ,"SiChannel.fPairArrayIndex" ,"SiChannel.fEnergy2" ,"SiChannel.fPosition.fZ" ,"SiChannel.fPhi1" ,"SiChannel.fPhi2" ,"SiChannel.fTheta1" ,"SiChannel.fTheta2" ,"SiChannel.fEnergy2:SiChannel.fStrip"};
        int nx, ny, n_draw_SiChannel = drawMembers_SiChannel.size();
        if (n_draw_SiChannel>0) {
            painter -> PreDividePad(n_draw_SiChannel, nx, ny);
            auto i_draw_SiChannel = 1;
            auto cvs_SiChannel = painter->CanvasResize("cvs_SiChannel", 500*nx, 380*ny, 1.0);
            painter -> DividePad(cvs_SiChannel, n_draw_SiChannel);
            for (auto member : drawMembers_SiChannel)
            {
                std::cout << "Draw: " << member << std::endl;
                cvs_SiChannel->cd(i_draw_SiChannel++);
                if (member.Contains(":"))
                    fReadTree->Draw(member, "", "colz");
                else
                    fReadTree->Draw(member);
            }
            cvs_SiChannel->Modified();
            cvs_SiChannel->Update();
        }
    }

    if (fActiveSiHit) {
        // SiHit : SKSiHit
        // reference: https://lilak-project.github.io/lilak_doxygen/classSKSiHit.html
        std::vector<TString> drawMembers_SiHit = {"SiHit.fDetID" ,"SiHit.fJunctionStrip" ,"SiHit.fOhmicStrip" ,"SiHit.fKeyEnergy" ,"SiHit.fEnergy" ,"SiHit.fEnergyLeft" ,"SiHit.fEnergyRight" ,"SiHit.fEnergyOhmic" ,"SiHit.fStripPosition" ,"SiHit.fRelativeZ" ,"SiHit.fX" ,"SiHit.fPhi" ,"SiHit.fTheta" ,"SiHit.fRelativeZdE" ,"SiHit.fEnergy:SiHit.fTheta" ,"SiHit.fEnergy:SiHit.fX"};
        int nx, ny, n_draw_SiHit = drawMembers_SiHit.size();
        if (n_draw_SiHit>0) {
            painter -> PreDividePad(n_draw_SiHit, nx, ny);
            auto i_draw_SiHit = 1;
            auto cvs_SiHit = painter->CanvasResize("cvs_SiHit", 500*nx, 380*ny, 1.0);
            painter -> DividePad(cvs_SiHit, n_draw_SiHit);
            for (auto member : drawMembers_SiHit)
            {
                std::cout << "Draw: " << member << std::endl;
                cvs_SiHit->cd(i_draw_SiHit++);
                if (member.Contains(":"))
                    fReadTree->Draw(member, "", "colz");
                else
                    fReadTree->Draw(member);
            }
            cvs_SiHit->Modified();
            cvs_SiHit->Update();
        }
    }


    //===============================================================================
    // XXX-2 USER EDIT AREA END
    //===============================================================================
}

void read_data(Long64_t maxEvents, int dump, Long64_t printAfter)
{
    if (fReadTree == nullptr) {
        std::cout << "No event tree is loaded." << std::endl;
        return;
    }

    auto numEntries = fReadTree->GetEntries();
    auto numLoop = numEntries;
    if (maxEvents >= 0 && maxEvents < numLoop)
        numLoop = maxEvents;
    if (dump > 0)
        numLoop = dump;

    std::cout << "# read_data" << std::endl;
    std::cout << "numEntries: " << numEntries << std::endl;
    std::cout << "maxEvents: " << maxEvents << std::endl;
    std::cout << "dump: " << dump << std::endl;
    std::cout << "printAfter: " << printAfter << std::endl;
    std::cout << "numLoop: " << numLoop << std::endl;

    for (auto entry = 0LL; entry < numLoop; ++entry) {
        if (printAfter > 0 && entry % printAfter == 0)
            std::cout << "entry: " << entry << " / " << numLoop << std::endl;
        fReadTree->GetEntry(entry);

        //===============================================================================
        // XXX-3 USER EDIT AREA BEGIN: inspect FrameHeader branch here.
        //===============================================================================
        // FrameHeader : LKEventHeader
        // reference: https://lilak-project.github.io/lilak_doxygen/classLKEventHeader.html
        auto num_FrameHeader = (fFrameHeaderArray != nullptr ? fFrameHeaderArray->GetEntriesFast() : 0);
        for (auto i_FrameHeader = 0; i_FrameHeader < num_FrameHeader; ++i_FrameHeader) {
            auto el_FrameHeader = (LKEventHeader*) fFrameHeaderArray->At(i_FrameHeader);
            if (el_FrameHeader == nullptr)
                continue;
            if (dump > 0) {
                el_FrameHeader->Print();
                auto value_GetEventNumber = el_FrameHeader->GetEventNumber();
                auto value_GetBufferSize = el_FrameHeader->GetBufferSize();
                auto value_GetEventTime = el_FrameHeader->GetEventTime();
            }
        }
        //===============================================================================
        // XXX-3 USER EDIT AREA END
        //===============================================================================

        //===============================================================================
        // XXX-4 USER EDIT AREA BEGIN: inspect RawData branch here.
        //===============================================================================
        // RawData : GETChannel
        // reference: https://lilak-project.github.io/lilak_doxygen/classGETChannel.html
        auto num_RawData = (fRawDataArray != nullptr ? fRawDataArray->GetEntriesFast() : 0);
        for (auto i_RawData = 0; i_RawData < num_RawData; ++i_RawData) {
            auto el_RawData = (GETChannel*) fRawDataArray->At(i_RawData);
            if (el_RawData == nullptr)
                continue;
            if (dump > 0) {
                el_RawData->Print();
                auto value_GetCobo = el_RawData->GetCobo();
                auto value_GetAsad = el_RawData->GetAsad();
                auto value_GetAget = el_RawData->GetAget();
                auto value_GetChan = el_RawData->GetChan();
                auto value_GetCAAC = el_RawData->GetCAAC();
                auto value_GetChannelID = el_RawData->GetChannelID();
                auto value_GetDetID = el_RawData->GetDetID();
                auto value_GetPadID = el_RawData->GetPadID();
                auto value_GetTime = el_RawData->GetTime();
                auto value_GetEnergy = el_RawData->GetEnergy();
                auto value_GetPedestal = el_RawData->GetPedestal();
                auto value_GetNoiseScale = el_RawData->GetNoiseScale();
                auto value_GetNumHits = el_RawData->GetNumHits();
                auto value_GetIntegral = el_RawData->GetIntegral();
            }
        }
        //===============================================================================
        // XXX-4 USER EDIT AREA END
        //===============================================================================

        //===============================================================================
        // XXX-5 USER EDIT AREA BEGIN: inspect SiChannel branch here.
        //===============================================================================
        // SiChannel : LKSiChannel
        // reference: https://lilak-project.github.io/lilak_doxygen/classLKSiChannel.html
        auto num_SiChannel = (fSiChannelArray != nullptr ? fSiChannelArray->GetEntriesFast() : 0);
        for (auto i_SiChannel = 0; i_SiChannel < num_SiChannel; ++i_SiChannel) {
            auto el_SiChannel = (LKSiChannel*) fSiChannelArray->At(i_SiChannel);
            if (el_SiChannel == nullptr)
                continue;
            if (dump > 0) {
                el_SiChannel->Print();
                auto value_GetLocalID = el_SiChannel->GetLocalID();
                auto value_GetSide = el_SiChannel->GetSide();
                auto value_GetStrip = el_SiChannel->GetStrip();
                auto value_GetDirection = el_SiChannel->GetDirection();
                auto value_GetInverted = el_SiChannel->GetInverted();
                auto value_GetDetID = el_SiChannel->GetDetID();
                auto value_GetPadID = el_SiChannel->GetPadID();
                auto value_GetPairArrayIndex = el_SiChannel->GetPairArrayIndex();
                auto value_GetZ = el_SiChannel->GetZ();
                auto value_GetRadius = el_SiChannel->GetRadius();
                auto value_GetPhi0 = el_SiChannel->GetPhi0();
                auto value_GetPhi1 = el_SiChannel->GetPhi1();
                auto value_GetPhi2 = el_SiChannel->GetPhi2();
                auto value_GetTheta0 = el_SiChannel->GetTheta0();
                auto value_GetTheta1 = el_SiChannel->GetTheta1();
                auto value_GetTheta2 = el_SiChannel->GetTheta2();
                auto value_GetEnergy1 = el_SiChannel->GetEnergy1();
                auto value_GetEnergy2 = el_SiChannel->GetEnergy2();
                auto value_GetEnergyPos = el_SiChannel->GetEnergyPos();
                auto value_GetEnergySum = el_SiChannel->GetEnergySum();
            }
        }
        //===============================================================================
        // XXX-5 USER EDIT AREA END
        //===============================================================================

        //===============================================================================
        // XXX-6 USER EDIT AREA BEGIN: inspect SiHit branch here.
        //===============================================================================
        // SiHit : SKSiHit
        // reference: https://lilak-project.github.io/lilak_doxygen/classSKSiHit.html
        auto num_SiHit = (fSiHitArray != nullptr ? fSiHitArray->GetEntriesFast() : 0);
        for (auto i_SiHit = 0; i_SiHit < num_SiHit; ++i_SiHit) {
            auto el_SiHit = (SKSiHit*) fSiHitArray->At(i_SiHit);
            if (el_SiHit == nullptr)
                continue;
            if (dump > 0) {
                el_SiHit->Print();
                auto value_GetDetID = el_SiHit->GetDetID();
                auto value_GetJunctionStrip = el_SiHit->GetJunctionStrip();
                auto value_GetOhmicStrip = el_SiHit->GetOhmicStrip();
                auto value_GetKeyEnergy = el_SiHit->GetKeyEnergy();
                auto value_GetE = el_SiHit->GetE();
                auto value_GetEnergy = el_SiHit->GetEnergy();
                auto value_GetEnergyTotalOhmic = el_SiHit->GetEnergyTotalOhmic();
                auto value_GetEnergyLeft = el_SiHit->GetEnergyLeft();
                auto value_GetEnergyRight = el_SiHit->GetEnergyRight();
                auto value_GetEnergyOhmic = el_SiHit->GetEnergyOhmic();
                auto value_GetStripPosition = el_SiHit->GetStripPosition();
                auto value_GetDetectorZ = el_SiHit->GetDetectorZ();
                auto value_GetX = el_SiHit->GetX();
                auto value_GetPhi = el_SiHit->GetPhi();
                auto value_GetTheta = el_SiHit->GetTheta();
            }
        }
        //===============================================================================
        // XXX-6 USER EDIT AREA END
        //===============================================================================
    }
}
