LKRun/Name  pre_li7  # name of the run
LKRun/RunID  111  # run number

bnnADC 500, 0, 4000
bnnVoltage 200, 0, 220
bnnEnergy 500, 0, 6

bnnVoltageBB10 200, 5, 70
bnnEnergyBB10 500, 5.45, 5.55
bnnResolutionBB10 500, 0, 0.15
bnnResolutionBB10J 100, 0.010, 0.030
bnnResolutionBB10O 100, 0.05, 0.095
bnnLeakageCurrentBB10 500, 0, 1

bnnVoltageQQQ5 200, 70, 210
bnnEnergyQQQ5 500, 3.15, 3.2
bnnResolutionQQQ5 500, 0, 0.15
bnnResolutionQQQ5J 500, 0.0, 0.04
bnnResolutionQQQ5O 500, 0.025, 0.045
bnnLeakageCurrentQQQ5 500, 0, 1

bestBiasBandHalfWidth 2.5

fitStdDevRange 5
