<common_run   common_run.mac

#si_array/MappingPath   mapping_ko2520

######################################
lilak/add   LKGETConversionTask
lilak/add   LKSetSiChannelTask
lilak/run   1
######################################

LKRun/Tag         reco
LKRun/SearchRun   mfm  # search input files with LKRun/RunID. opt=mfm: search mfm files, opt=[tag]: search run_runNo.*.[tag].root
LKRun/InputPath   data_merged
LKRun/EventCountForMessage 1

#SKSiArrayPlane/jumpEventSize  50000

#SKDrawEventStatisticsTask/binning_energy 500, 0, 4100
#SKDrawEventStatisticsTask/binning_theta  50, 50, 100

#stark/EnergyCalibrationFile   {lilak_common}/stark_ecal_par.199_303.RAON2024_40Arp.root
#stark/EnergyCalibrationFile   {lilak_common}/stark_ecal_par.199_303.RAON2024_40Arp.root
#stark/Mapping1                {lilak_common}/starkmap_input.RAON2024_25Na.txt
#stark/Mapping2                {lilak_common}/starkmap_output.RAON2024_25Na.txt
#stark/Mapping1 stark_mapping_half_merger_test.detector.txt
#stark/Mapping2 stark_mapping_half_merger_test.channel.txt
#stark/pulseFile               {lilak_common}/pulseReference.root
#lilak/add   STARK
