#<common_run   common_run.mac
<common_run get_common.mac

#si_array/MappingPath   mapping_ko2520

######################################
lilak/add  LKCoboFrameMergerTask  # add task or detector class
lilak/add  LKSetSiChannelTask
lilak/run  0
######################################

LKRun/Tag         reco
LKRun/SearchRun   mfm
LKRun/InputPath   data_raw
LKRun/EventCountForMessage 1000

#SKSiArrayPlane/jumpEventSize  50000

LKFrameBuilder/MaxCobo 1  # maximum number of CoBo
LKFrameBuilder/MaxAsad 4  # maximum number of AsAd in one CoBo
LKFrameBuilder/MaxAget 4  # maximum number of AGET in one AsAd
LKFrameBuilder/MaxChannels 68  # maximum number of channels in AGET
