// This macro was generated by:
//   lilak read /root/lilak/stark/macros_ko2520_onsite/data_reco/compass_0317.reco.root
//
// Purpose:
//   Open a LILAK output ROOT file, connect the event tree branches,
//   read ParameterContainer and RunHeader, and provide an editable event-loop skeleton.
//
// Use dump > 0 to loop over only dump entries and call Print() for every branch element.
// Use dump = 0 for normal looping without automatic element Print().
// Getter examples come from meta/lilak_read_getters.conf.
// Format:
//   ClassName    type Method(), type member, ...
// Draw examples come from meta/lilak_read_members.conf.
//
// XXX USER EDIT AREA INDEX:
//   XXX-1: Global run controls. Change fInputFileName, fMaxEvents, fDump, fPrintAfter, fRunLoop, fDrawBranch.
//   XXX-2: Draw commands. Add fReadTree->Draw("...") examples in draw_branch().
//   XXX-3: Branch loop for ComW1Channel (LKComW1Channel).
//   XXX-4: Branch loop for ComChannel (LKComChannel).
//   XXX-5: Branch loop for ComW1Hit (LKComW1Hit).
//   XXX-6: Branch loop for ComHit (LKComHit).


//===============================================================================
// XXX-1 USER EDIT AREA BEGIN: global input file and loop controls.
//===============================================================================
TString fInputFileName = "/root/lilak/stark/macros_ko2520_onsite/data_reco/compass_0317.reco.root";
Long64_t fMaxEvents = -1;
int fDump = 0;
Long64_t fPrintAfter = 2000;
bool fRunLoop = true;
bool fDrawBranch = true;
bool fActiveComW1Channel = true;
bool fActiveComChannel = true;
bool fActiveComW1Hit = true;
bool fActiveComHit = true;

//===============================================================================
// XXX-1 USER EDIT AREA END
//===============================================================================

TFile* fReadFile = nullptr;
TObject* fReadPar = nullptr;
TObject* fReadRunHeader = nullptr;
TTree* fReadTree = nullptr;

TClonesArray* fComW1ChannelArray = nullptr;
TClonesArray* fComChannelArray = nullptr;
TClonesArray* fComW1HitArray = nullptr;
TClonesArray* fComHitArray = nullptr;

void open_file_and_set_branch(TString fileName);
void read_header_and_parameters(bool print = false);
void read_data(Long64_t maxEvents = -1, int dump = 0, Long64_t printAfter = 2000);
void draw_branch();

void read_compass_0317_reco()
{
    open_file_and_set_branch(fInputFileName);
    read_header_and_parameters();
    if (fRunLoop)
        read_data(fMaxEvents, fDump, fPrintAfter);
    if (fDrawBranch)
        draw_branch();
}

void open_file_and_set_branch(TString fileName)
{
    fReadFile = TFile::Open(fileName, "read");
    if (fReadFile == nullptr || fReadFile->IsZombie()) {
        std::cout << "Cannot open " << fileName << std::endl;
        fReadFile = nullptr;
        return;
    }

    fReadTree = dynamic_cast<TTree*>(fReadFile->Get("event"));
    if (fReadTree == nullptr) {
        TIter nextKey(fReadFile->GetListOfKeys());
        TKey* key = nullptr;
        while ((key = dynamic_cast<TKey*>(nextKey())) != nullptr) {
            auto object = key->ReadObj();
            fReadTree = dynamic_cast<TTree*>(object);
            if (fReadTree != nullptr)
                break;
        }
    }
    if (fReadTree == nullptr) {
        std::cout << "No TTree found in " << fileName << std::endl;
        return;
    }

    fReadTree->SetBranchAddress("ComW1Channel", &fComW1ChannelArray);
    fReadTree->SetBranchAddress("ComChannel", &fComChannelArray);
    fReadTree->SetBranchAddress("ComW1Hit", &fComW1HitArray);
    fReadTree->SetBranchAddress("ComHit", &fComHitArray);

}

void read_header_and_parameters(bool print)
{
    if (fReadFile == nullptr) {
        std::cout << "No file is open." << std::endl;
        return;
    }

    fReadPar = fReadFile->Get("ParameterContainer");
    fReadRunHeader = fReadFile->Get("RunHeader");

    std::cout << "# LILAK output file" << std::endl;
    std::cout << "File: " << fReadFile->GetName() << std::endl;
    std::cout << "ParameterContainer: " << (fReadPar != nullptr ? "loaded" : "missing") << std::endl;
    std::cout << "RunHeader: " << (fReadRunHeader != nullptr ? "loaded" : "missing") << std::endl;
    std::cout << "Event tree: " << (fReadTree != nullptr ? fReadTree->GetName() : "missing") << std::endl;
    std::cout << "# Branches" << std::endl;
    std::cout << "  ComW1Channel : TClonesArray<LKComW1Channel>" << std::endl;
    std::cout << "  ComChannel : TClonesArray<LKComChannel>" << std::endl;
    std::cout << "  ComW1Hit : TClonesArray<LKComW1Hit>" << std::endl;
    std::cout << "  ComHit : TClonesArray<LKComHit>" << std::endl;

    if (!print)
        return;

    if (fReadPar != nullptr) {
        std::cout << std::endl << "# ParameterContainer" << std::endl;
        fReadPar->Print();
    }
    if (fReadRunHeader != nullptr) {
        std::cout << std::endl << "# RunHeader" << std::endl;
        fReadRunHeader->Print();
    }
}

void draw_branch()
{
    if (fReadTree == nullptr) {
        std::cout << "No event tree is loaded." << std::endl;
        return;
    }
    auto painter = LKPainter::GetPainter();

    //===============================================================================
    // XXX-2 USER EDIT AREA BEGIN: add branch drawing commands here.
    //===============================================================================
    // Examples:
    //   fReadTree->Draw("RawData.fChannel");
    //   fReadTree->Draw("SiHit.fEnergy");
    //   fReadTree->Draw("SiHit.fEnergy:SiHit.fX");
    //
    // Edit or comment out generated examples below for this file.
    // No draw member examples configured for LKComW1Channel.
    // Add entries to meta/lilak_read_members.conf to generate examples for ComW1Channel.
    // fReadTree->Draw("ComW1Channel.member");

    // No draw member examples configured for LKComChannel.
    // Add entries to meta/lilak_read_members.conf to generate examples for ComChannel.
    // fReadTree->Draw("ComChannel.member");

    // No draw member examples configured for LKComW1Hit.
    // Add entries to meta/lilak_read_members.conf to generate examples for ComW1Hit.
    // fReadTree->Draw("ComW1Hit.member");

    // No draw member examples configured for LKComHit.
    // Add entries to meta/lilak_read_members.conf to generate examples for ComHit.
    // fReadTree->Draw("ComHit.member");


    //===============================================================================
    // XXX-2 USER EDIT AREA END
    //===============================================================================
}

void read_data(Long64_t maxEvents, int dump, Long64_t printAfter)
{
    if (fReadTree == nullptr) {
        std::cout << "No event tree is loaded." << std::endl;
        return;
    }

    auto numEntries = fReadTree->GetEntries();
    auto numLoop = numEntries;
    if (maxEvents >= 0 && maxEvents < numLoop)
        numLoop = maxEvents;
    if (dump > 0)
        numLoop = dump;

    std::cout << "# read_data" << std::endl;
    std::cout << "numEntries: " << numEntries << std::endl;
    std::cout << "maxEvents: " << maxEvents << std::endl;
    std::cout << "dump: " << dump << std::endl;
    std::cout << "printAfter: " << printAfter << std::endl;
    std::cout << "numLoop: " << numLoop << std::endl;

    auto top1 = new LKDrawingGroup("w1");
    auto top2 = new LKDrawingGroup("w1");
    //auto hist_mult = new TH1D("hist_mult","",10,0,10); top1 -> AddHist(hist_mult);
    //auto hist_ec = new TH2D("hist_ec","",20,0,20,1000,0,7000); top1 -> AddHist(hist_ec);
    //auto hist_ec1 = new TH2D("hist_ec1","",20,0,20,1000,0,7000); top1 -> AddHist(hist_ec1);
    //auto hist_ec2 = new TH2D("hist_ec2","",20,0,20,1000,0,7000); top1 -> AddHist(hist_ec2);
    //auto hist_ec3 = new TH2D("hist_ec3","",20,0,20,1000,0,7000); top1 -> AddHist(hist_ec3);
    //auto hist_ec4 = new TH2D("hist_ec4","",20,0,20,1000,0,7000); top1 -> AddHist(hist_ec4);
    //auto hist_energy = new TH1D("hist_energy","",1000,0,7000); top1 -> AddHist(hist_energy);
    //auto hist_energy1 = new TH1D("hist_energy1","",1000,0,7000); top1 -> AddHist(hist_energy1);
    //auto hist_energy2 = new TH1D("hist_energy2","",1000,0,7000); top1 -> AddHist(hist_energy2);
    //auto hist_energy3 = new TH1D("hist_energy3","",1000,0,7000); top1 -> AddHist(hist_energy3);
    //auto hist_energy4 = new TH1D("hist_energy4","",1000,0,7000); top1 -> AddHist(hist_energy4);
    //auto hist_energy5 = new TH1D("hist_energy5","",1000,0,7000); top1 -> AddHist(hist_energy5);
    TH1D *hist_e1[4] = {0}; for (auto mult:{1,2,3,4}) { hist_e1[mult-1] = new TH1D(Form("hist_e1_m%d",mult),"",1000,0,7000); top1 -> AddHist(hist_e1[mult-1]); }
    TH2D *hist_ec[4] = {0}; for (auto mult:{1,2,3,4}) { hist_ec[mult-1] = new TH2D(Form("hist_ec_m%d",mult),"",32,0,32,1000,0,7000); top2 -> AddHist(hist_ec[mult-1]); }

    for (auto entry = 0LL; entry < numLoop; ++entry) {
        if (printAfter > 0 && entry % printAfter == 0)
            std::cout << "entry: " << entry << " / " << numLoop << std::endl;
        fReadTree->GetEntry(entry);

        //===============================================================================
        // XXX-3 USER EDIT AREA BEGIN: inspect ComW1Channel branch here.
        //===============================================================================
        // ComW1Channel : LKComW1Channel
        // reference: https://lilak-project.github.io/lilak_doxygen/classLKComW1Channel.html
        auto num_ComW1Channel = (fComW1ChannelArray != nullptr ? fComW1ChannelArray->GetEntriesFast() : 0);
        if (num_ComW1Channel<2) continue;
        //else cout << num_ComW1Channel << endl;
        //hist_mult -> Fill(num_ComW1Channel);
        for (auto i_ComW1Channel = 0; i_ComW1Channel < num_ComW1Channel; ++i_ComW1Channel) {
            auto el_ComW1Channel = (LKComW1Channel*) fComW1ChannelArray->At(i_ComW1Channel);
            if (el_ComW1Channel == nullptr)
                continue;
            if (dump > 0) {
                el_ComW1Channel->Print();
                // No getter examples configured for LKComW1Channel.
                // Add entries to meta/lilak_read_getters.conf to generate examples here.
            }
            //cout << "  " << el_ComW1Channel->fDetectorID  << " " << el_ComW1Channel->fStrip << " " << el_ComW1Channel->fEnergy << endl;
            auto energy = el_ComW1Channel->fEnergy;
            auto side = el_ComW1Channel->fSide;
            auto strip = el_ComW1Channel->fStrip;
            for (auto mult:{1,2,3,4}) { if (num_ComW1Channel==mult) { hist_e1[mult-1] -> Fill(energy); } }
            for (auto mult:{1,2,3,4}) { if (num_ComW1Channel==mult) { hist_ec[mult-1] -> Fill(strip+side*16,energy); } }
            //hist_energy -> Fill(el_ComW1Channel->fEnergy);
            //if (num_ComW1Channel==1) hist_energy1 -> Fill(el_ComW1Channel->fEnergy);
            //if (num_ComW1Channel==2) hist_energy2 -> Fill(el_ComW1Channel->fEnergy);
            //if (num_ComW1Channel==3) hist_energy3 -> Fill(el_ComW1Channel->fEnergy);
            //if (num_ComW1Channel==4) hist_energy4 -> Fill(el_ComW1Channel->fEnergy);
            //if (num_ComW1Channel==5) hist_energy5 -> Fill(el_ComW1Channel->fEnergy);
            //hist_ec -> Fill(el_ComW1Channel->fStrip ,el_ComW1Channel->fEnergy);
            //if (num_ComW1Channel==1) hist_ec1 -> Fill(el_ComW1Channel->fStrip,el_ComW1Channel->fEnergy);
            //if (num_ComW1Channel==2) hist_ec2 -> Fill(el_ComW1Channel->fStrip,el_ComW1Channel->fEnergy);
            //if (num_ComW1Channel==3) hist_ec3 -> Fill(el_ComW1Channel->fStrip,el_ComW1Channel->fEnergy);
            //if (num_ComW1Channel==4) hist_ec4 -> Fill(el_ComW1Channel->fStrip,el_ComW1Channel->fEnergy);
        }
        //===============================================================================
        // XXX-3 USER EDIT AREA END
        //===============================================================================

        //===============================================================================
        // XXX-4 USER EDIT AREA BEGIN: inspect ComChannel branch here.
        //===============================================================================
        // ComChannel : LKComChannel
        // reference: https://lilak-project.github.io/lilak_doxygen/classLKComChannel.html
        auto num_ComChannel = (fComChannelArray != nullptr ? fComChannelArray->GetEntriesFast() : 0);
        for (auto i_ComChannel = 0; i_ComChannel < num_ComChannel; ++i_ComChannel) {
            auto el_ComChannel = (LKComChannel*) fComChannelArray->At(i_ComChannel);
            if (el_ComChannel == nullptr)
                continue;
            if (dump > 0) {
                el_ComChannel->Print();
                // No getter examples configured for LKComChannel.
                // Add entries to meta/lilak_read_getters.conf to generate examples here.
            }
        }
        //===============================================================================
        // XXX-4 USER EDIT AREA END
        //===============================================================================

        //===============================================================================
        // XXX-5 USER EDIT AREA BEGIN: inspect ComW1Hit branch here.
        //===============================================================================
        // ComW1Hit : LKComW1Hit
        // reference: https://lilak-project.github.io/lilak_doxygen/classLKComW1Hit.html
        auto num_ComW1Hit = (fComW1HitArray != nullptr ? fComW1HitArray->GetEntriesFast() : 0);
        for (auto i_ComW1Hit = 0; i_ComW1Hit < num_ComW1Hit; ++i_ComW1Hit) {
            auto el_ComW1Hit = (LKComW1Hit*) fComW1HitArray->At(i_ComW1Hit);
            if (el_ComW1Hit == nullptr)
                continue;
            if (dump > 0) {
                el_ComW1Hit->Print();
                // No getter examples configured for LKComW1Hit.
                // Add entries to meta/lilak_read_getters.conf to generate examples here.
            }
        }
        //===============================================================================
        // XXX-5 USER EDIT AREA END
        //===============================================================================

        //===============================================================================
        // XXX-6 USER EDIT AREA BEGIN: inspect ComHit branch here.
        //===============================================================================
        // ComHit : LKComHit
        // reference: https://lilak-project.github.io/lilak_doxygen/classLKComHit.html
        auto num_ComHit = (fComHitArray != nullptr ? fComHitArray->GetEntriesFast() : 0);
        for (auto i_ComHit = 0; i_ComHit < num_ComHit; ++i_ComHit) {
            auto el_ComHit = (LKComHit*) fComHitArray->At(i_ComHit);
            if (el_ComHit == nullptr)
                continue;
            if (dump > 0) {
                el_ComHit->Print();
                // No getter examples configured for LKComHit.
                // Add entries to meta/lilak_read_getters.conf to generate examples here.
            }
        }
        //===============================================================================
        // XXX-6 USER EDIT AREA END
        //===============================================================================
    }

    top1 -> Draw();
    top1 -> GetCanvas() -> SaveAs("data_reco/read_compass_0317_reco.1.root");
    top2 -> Draw();
    top2 -> GetCanvas() -> SaveAs("data_reco/read_compass_0317_reco.2.root");
}
