<common_run  get_common.mac

lilak/add  LKCoboFrameMergerTask  # add task or detector class
lilak/add  LKSetSiChannelTask
lilak/run  10

LKRun/EventCountForMessage  1

LKRun/Run 67
LKRun/SearchRun mfm
LKRun/InputPath data_get
LKRun/Tag pulser  # tag
LKRun/EventCountForMessage 100

#LKCoboFrameMergerTask/InputFileName data_get/run_0067.dat.28-08-26_10h13m46s

LKFrameBuilder/MaxCobo 1  # maximum number of CoBo
LKFrameBuilder/MaxAsad 4  # maximum number of AsAd in one CoBo
LKFrameBuilder/MaxAget 4  # maximum number of AGET in one AsAd
LKFrameBuilder/MaxChannels 68  # maximum number of channels in AGET

LKSetSiChannelTask/pulser_analysis true
