<common_run  common_get.mac

lilak/add     LKCoboFrameMergerTask  # add task or detector class
lilak/add     LKSetSiChannelTask
lilak/online  1000

#LKRun/Run  9999
LKRun/Tag  online  # tag
LKRun/EventCountForMessage    100

LKCoboFrameMergerTask/InputFileName  online
LKCoboFrameMergerTask/watcherIP  192.168.40.1 192.168.40.1
LKCoboFrameMergerTask/watcherPort  10202 10203

#LKMFMConversionTask/InputFileName  online
#LKMFMConversionTask/watcherIP  192.168.40.1
#LKMFMConversionTask/watcherPort  10202
#LKMFMConversionTask/sleepBeforeConnect  1
#LKMFMConversionTask/breakAfterFailNumber  20

LKFrameBuilder/MaxCobo  1  # maximum number of CoBo
LKFrameBuilder/MaxAsad  4  # maximum number of AsAd in one CoBo
LKFrameBuilder/MaxAget  4  # maximum number of AGET in one AsAd
LKFrameBuilder/MaxChannels  68  # maximum number of channels in AGET
