<stark_configs         config_stark.mac

LKRun/Name             stark
LKRun/InputFile        /home/ejungwoo/data/stark/conv/stark_0303.conv.root
#LKRun/InputFile        /home/ejungwoo/data/stark/conv/stark_0199.conv.root
#LKRun/InputFile        /home/ejungwoo/data/stark/conv/stark_0253.conv.root
LKRun/Tag              reco
LKRun/OutputPath       ./data/
LKRun/EventCountForMessage 20000

persistency/SiChannel  true
